///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OtpModel {
/*
{
  "success": true,
  "data": null,
  "message": "User Detail."
} 
*/

  dynamic success;
  String data;
  String message;

  OtpModel({
    this.success,
    this.data,
    this.message,
  });
  OtpModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = json['data']?.toString();
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['data'] = this.data;
    data['message'] = message;
    return data;
  }
}
