///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LanguagesModelLevels {
/*
{
  "id": 100,
  "name": "Introduction",
  "description": "Introduction to Shona Language",
  "imageContentType": null,
  "orderIndex": 1,
  "imageContentLength": 0,
  "numberOfLessons": 0,
  "language": null
} 
*/

  int? id;
  String? name;
  String? description;
  String? imageContentType;
  int? orderIndex;
  int? imageContentLength;
  int? numberOfLessons;
  String? language;

  LanguagesModelLevels({
    this.id,
    this.name,
    this.description,
    this.imageContentType,
    this.orderIndex,
    this.imageContentLength,
    this.numberOfLessons,
    this.language,
  });
  LanguagesModelLevels.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    description = json['description']?.toString();
    imageContentType = json['imageContentType']?.toString();
    orderIndex = json['orderIndex']?.toInt();
    imageContentLength = json['imageContentLength']?.toInt();
    numberOfLessons = json['numberOfLessons']?.toInt();
    language = json['language']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['description'] = description;
    data['imageContentType'] = imageContentType;
    data['orderIndex'] = orderIndex;
    data['imageContentLength'] = imageContentLength;
    data['numberOfLessons'] = numberOfLessons;
    data['language'] = language;
    return data;
  }
}

class LanguagesModel {
/*
{
  "id": 10,
  "name": "Shona",
  "description": "Shona Language",
  "imageContentType": null,
  "imageContentLength": 0,
  "levels": [
    {
      "id": 100,
      "name": "Introduction",
      "description": "Introduction to Shona Language",
      "imageContentType": null,
      "orderIndex": 1,
      "imageContentLength": 0,
      "numberOfLessons": 0,
      "language": null
    }
  ]
} 
*/

  int? id;
  String? name;
  String? description;
  String? imageContentType;
  int? imageContentLength;
  List<LanguagesModelLevels?>? levels;

  LanguagesModel({
    this.id,
    this.name,
    this.description,
    this.imageContentType,
    this.imageContentLength,
    this.levels,
  });
  LanguagesModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    description = json['description']?.toString();
    imageContentType = json['imageContentType']?.toString();
    imageContentLength = json['imageContentLength']?.toInt();
    if (json['levels'] != null) {
      final v = json['levels'];
      final arr0 = <LanguagesModelLevels>[];
      v.forEach((v) {
        arr0.add(LanguagesModelLevels.fromJson(v));
      });
      levels = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['description'] = description;
    data['imageContentType'] = imageContentType;
    data['imageContentLength'] = imageContentLength;
    if (levels != null) {
      final v = levels;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['levels'] = arr0;
    }
    return data;
  }
}
